# Generated by Django 3.1.7 on 2021-03-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=1)),
                ('comentario', models.CharField(max_length=500)),
                ('estado', models.BooleanField(null=True)),
                ('usuario_denunciado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario')),
                ('usuario_denunciante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario')),
            ],
        ),
    ]
