# Generated by Django 3.1.7 on 2021-03-02 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_nombre_cuenta'),
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='usuario_denunciante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario'),
        ),
    ]
