# Generated by Django 3.1.7 on 2021-03-02 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_nombre_cuenta'),
        ('denuncia', '0002_denuncia_usuario_denunciante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='usuario_denunciado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario'),
        ),
    ]
