# Generated by Django 3.1.7 on 2021-03-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('estado', models.BooleanField()),
                ('usuario_publicista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario')),
            ],
        ),
    ]
