# Generated by Django 3.1.7 on 2021-03-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id_correo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('futuro_duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mascota.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=250, null=True)),
                ('fecha', models.DateField()),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mensaje.correo')),
                ('usuario_emisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario')),
            ],
        ),
    ]
