# Generated by Django 3.1.7 on 2021-02-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Denuncia',
            fields=[
                ('id_datos_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=1)),
                ('comentario', models.CharField(max_length=500)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Mascota',
            fields=[
                ('id_datos_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.BooleanField()),
                ('especie', models.CharField(max_length=25)),
                ('raza', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Postulante',
            fields=[
                ('id_datos_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Publicacion',
            fields=[
                ('id_datos_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id_denuncias', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_Postulante',
            fields=[
                ('id_nodo_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('datos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.datos_postulante')),
                ('nodo_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_postulante')),
                ('nodo_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_Publicacion',
            fields=[
                ('id_nodo_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('datos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.datos_publicacion')),
                ('nodo_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_publicacion')),
                ('nodo_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id_publicaciones', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('primer_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_publicacion')),
                ('ultimo_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('contrasenia', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=50)),
                ('descripcion_propia', models.CharField(max_length=500, null=True)),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('denuncias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.denuncias')),
                ('publicaciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.publicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Postulantes',
            fields=[
                ('id_postulantes', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('primer_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_postulante')),
                ('ultimo_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_Mascota',
            fields=[
                ('id_nodo_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('datos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.datos_mascota')),
                ('nodo_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_mascota')),
                ('nodo_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo_Denuncia',
            fields=[
                ('id_nodo_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('datos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.datos_denuncia')),
                ('nodo_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_denuncia')),
                ('nodo_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascotas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('primer_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_mascota')),
                ('ultimo_nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_mascota')),
            ],
        ),
        migrations.AddField(
            model_name='denuncias',
            name='primer_nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_denuncia'),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='ultimo_nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.nodo_denuncia'),
        ),
        migrations.AddField(
            model_name='datos_publicacion',
            name='mascotas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.mascotas'),
        ),
        migrations.AddField(
            model_name='datos_postulante',
            name='usuario_postulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.usuarios'),
        ),
        migrations.AddField(
            model_name='datos_mascota',
            name='futuro_duenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.usuarios'),
        ),
        migrations.AddField(
            model_name='datos_mascota',
            name='postulantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.postulantes'),
        ),
        migrations.AddField(
            model_name='datos_denuncia',
            name='usuario_denunciado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Prueba.usuarios'),
        ),
    ]
