# Generated by Django 3.1.7 on 2021-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='datos_mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=30),
        ),
    ]
