# Generated by Django 3.1.7 on 2021-03-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0002_auto_20210228_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=9),
        ),
    ]
