# Generated by Django 3.1.7 on 2021-03-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=25)),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'macho'), ('hembra', 'hembra')], max_length=30)),
                ('raza', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(null=True)),
                ('futuro_duenio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario')),
                ('publicacion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publicacion.publicacion')),
            ],
        ),
    ]
