# Generated by Django 3.1.7 on 2021-03-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='id_datos_mascota',
            new_name='id_mascota',
        ),
    ]
