# Generated by Django 3.1.7 on 2021-03-02 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('mascota', '0002_auto_20210301_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='futuro_duenio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario'),
        ),
    ]
