# Generated by Django 3.1.7 on 2021-03-02 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_remove_publicacion_mascota'),
        ('mascota', '0003_mascota_futuro_duenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='publicacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publicacion.publicacion'),
        ),
    ]
