# Generated by Django 3.1.7 on 2021-03-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_cuenta',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
