# Generated by Django 3.1.7 on 2021-03-02 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=250, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publicacion.publicacion')),
                ('usuario_postulado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario')),
            ],
        ),
    ]
