# Generated by Django 3.1.7 on 2021-03-02 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20210301_2318'),
        ('postulante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='publicacion',
        ),
        migrations.AddField(
            model_name='postulante',
            name='mascota_postulado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mascota.mascota'),
        ),
    ]
