# Generated by Django 3.1.7 on 2021-03-02 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_nombre_cuenta'),
        ('postulante', '0002_auto_20210301_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='usuario_postulado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usuario.usuario'),
        ),
    ]
